In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50])

In [3]:
print(arr)

[10 20 30 40 50]


In [4]:
# get the dimension of array
arr.ndim

1

In [5]:
arr.shape

(5,)

In [7]:
arr_2d = np.array([
    [10,20,30,40,50],
    [100,200,300,400,500]
])

In [8]:
print(arr_2d)

[[ 10  20  30  40  50]
 [100 200 300 400 500]]


In [11]:
arr_2d.shape # says there are 2 rows and 5 columns

(2, 5)

In [13]:
len(arr_2d) # will give 2 because it interprets the 2d array by saying there are two arrays inside the main array

2

In [14]:
arr_2d.size # this will give the total number of all the nested elements in the array

10

In [15]:
type(arr_2d)

numpy.ndarray

In [16]:
arr_2d.dtype # see the type of data arr_2d is storing

dtype('int32')

<!-- Every element in the numpy array must be of the same type. -->

In [20]:
# Every element in the array must be of the same type and size.

In [21]:
# If an array's elements are also arrays, those inner arrays must have the same type and number of elements as each other.

In [26]:
np.array([1,'hello',True]) # numpy doesn't actually throw error if the types are different but rather converts the elements into same type, like here it will convert all the elements to string type

array(['1', 'hello', 'True'], dtype='<U11')

In [28]:
np.array(
    [[1,2],
    [5.5,6.7]]
) # here numpy will convert the integer type to float

array([[1. , 2. ],
       [5.5, 6.7]])

In [30]:
np.array(
    [[1,2,3,4],
    [5.5,6.7]]
) # if the inner array has different size then it gives an error

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [33]:
# create an array with 0 values

In [35]:
np.zeros(3) # this will create an array with one row and 3 columns whose all elemets default value will be floating 0
# or np.zeros(shape=3)

array([0., 0., 0.])

In [39]:
np.zeros(shape=(3,5)) # this will create an array with 3 rows and 5 columns whose all elemets default value will be floating 0
# we must pass shape argument and small bracket to define shape

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
np.zeros(shape=(3,5), dtype='int64') # this will create an array with 3 rows and 5 columns whose all elemets default value will be integer64 0
# we must pass shape argument and small bracket to define shape

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [42]:
np.full(shape = (3,5), fill_value = 'cat') # this will create an array with 3 rows and 5 columns whose all elemets default value will be string 'cat'

array([['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat'],
       ['cat', 'cat', 'cat', 'cat', 'cat']], dtype='<U3')

In [43]:
# print a pattern
np.arange(start=1, stop=5, step=1)

array([1, 2, 3, 4])

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# print random number for a certain size
np.random.randint(low = 1, high = 7, size = (2,3))

array([[5, 3, 1],
       [5, 4, 5]])

In [48]:
np.random.randint(low = 1, high = 7, size = (2,3))

array([[6, 2, 5],
       [4, 4, 1]])

In [57]:
arr1 = np.array([10,20,30,40,50])

In [50]:
arr1[1]

20

In [61]:
# arr1[0]=34

In [58]:
arr1

array([10, 20, 30, 40, 50])

In [62]:
arr1[-1]

50

In [63]:
# get multiple index value
arr1[[1,0]]

array([20, 10])

In [60]:
# slicing same as python list
arr1[:2] # give the elements from beginning of array to index 2 exclusive. Basically gives 0 and 1 index value

array([10, 20])

In [64]:
arr1[2:] # give the elements from index 2 to end of the array

array([30, 40, 50])

In [67]:
# collection[start:stop:step]
arr1[::2] # give the elements from index 0 to end by skipping to every next 2nd index so index 0,2,4 will be returned as 0,0+2,2+2 = 0,2,4

array([10, 30, 50])

In [71]:
arr1[[0,1,4]] = 1 # replaces index 0, 1 and 4 element value with 1

In [72]:
arr1

array([ 1,  1, 30, 40,  1])

In [70]:
arr1[1:4:2] # give the elements from index 1 to 4 by skipping to every next two indexes so index 1,3 will be returned as 1,1+2,3+2(5 wchich is out of bound so this is skipped) = 0,3

array([20, 40])

In [82]:
# Two dimensional array

In [85]:
arr2=np.array(
    [
        [5,10,15,10],
        [25,30,35,40],
        [45,50,55,60]
    ]
    )

In [78]:
arr2[1,2] # 1 then index row and 2th index column

35

In [80]:
arr2[0] # get first row of an array

array([ 5, 10, 15, 10])

In [81]:
arr2[0,None] # get only first array row of the array and no other columhn. Look closely there will be nested array but with only one first row

array([[ 5, 10, 15, 10]])

In [83]:
# Three dimensional array

In [86]:
arr3 = np.array([
    [
        [10,20],
        [30,40],
        [50,60]
    ],
        [
        [11,12],
        [13,14],
        [15,16]
    ]
])

In [87]:
arr3[0,:,1] = 5 # set first matrix's every row's first column to 5

In [88]:
arr3

array([[[10,  5],
        [30,  5],
        [50,  5]],

       [[11, 12],
        [13, 14],
        [15, 16]]])