In [1]:
import numpy as np

In [3]:
arr1 = np.array([[4,3], [1,0]])
arr2 = np.array([[1,2], [3,4]])

In [4]:
print(arr1)

[[4 3]
 [1 0]]


In [5]:
arr2

array([[1, 2],
       [3, 4]])

In [8]:
arr1 + arr2 # adds the corresponding indices values

array([[5, 5],
       [4, 4]])

In [9]:
# arthemtic multiplication
arr1 * arr2

array([[4, 6],
       [3, 0]])

In [10]:
# for matrix multiplication
arr1 @ arr2

array([[13, 20],
       [ 1,  2]])

In [11]:
# add 5 to all elements of an array
arr1 + 5

array([[9, 8],
       [6, 5]])