# Setup for challenge 1

With your high school reunion fast approaching, you decide to get in shape and lose some weight. You record your weight every day for five weeks starting on Monday. Given these daily weights, build an array with your average weight per weekend.

In [2]:
import numpy as np

In [4]:
dailywts = 185 - np.arange(5*7) / 5
print(dailywts)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


### Solution

In [5]:
 np.arange(5*7)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34])

In [6]:
 np.arange(5*7) / 5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8])

In [18]:
# solution for average per weekend ie average weight for Sunday and Saturday of every 5 weeks
(dailywts[5::7] + dailywts[6::7] ) / 2

# dailywts[5::7]: This selects every 7th element starting from index 5. This corresponds to the weights on Saturdays.

# dailywts[6::7]: This selects every 7th element starting from index 6. This corresponds to the weights on Sundays.

# (dailywts[5::7] + dailywts[6::7]) / 2: This adds the weights on Saturdays and Sundays element-wise and then divides the result by 2 to calculate the average weight for each weekend.

# :7 skips to 7 indexes to go to next weekday

array([183.9, 182.5, 181.1, 179.7, 178.3])

In [16]:
# my solution for an average weight of every weekdays for 5 weeks
res = []
for i in range(5):
    res.append(np.average(dailywts[i*7 : i*7 + 7]))
res

[184.4, 183.0, 181.6, 180.2, 178.8]

# Setup for challenge 2

After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner. You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

In [19]:
import numpy as np

In [20]:
np.random.seed(5555)
gold = np.random.randint(low = 0, high = 10, size = (7,7))
print(gold)

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


In [21]:
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])
print(locs)

[[0 4]
 [2 2]
 [2 3]
 [5 1]
 [6 3]]


### Solutution

In [31]:
# my solution
res = []
for row in locs:
    # print(gold[row[0]][row[1]])
    res.append(gold[row[0]][row[1]])

print(res)

[2, 6, 2, 8, 2]


In [44]:
# author solution
gold[locs[: , 0], locs[:, 1]]

# locs[:, 0] provides the row indices.
# locs[:, 1] provides the column indices.
# So, gold[locs[:, 0], locs[:, 1]] extracts the values from the gold array at the specified locations.

array([2, 6, 2, 8, 2])

In [35]:
# explanation:

In [36]:
gold[0,4]

2

In [37]:
gold[2,2]

6

In [45]:
# for constructing answer of array:
gold[[0,2],[4,2]] # we pass the list of rows indices and then list of columns indices to get the values in one scoop
# to automate the rows and columns generation we can use split as gold[locs[: , 0], locs[:, 1]]

array([2, 6])

In [46]:
# Note:
# When you use gold[[0, 2], [4, 2]], it does not correspond to gold[0, 4] and gold[2, 2]. 
# Instead, it selects the elements at the specified pairs of indices. In this case, it is selecting gold[0, 4] and gold[2, 2].

# Setup for challenge 3

You decide to invest in a series of billboards along interstate 10 to advertise your stylish new chicken restaurant, Chic-fil-A. You buy three billboards evenly spaced starting on mile marker 17 and ending on mile marker 28. Then you buy another three billboards evenly spaced starting on mile marker 32 and ending on mile marker 36. In order, from mile marker 17 to 36, your billboards display these ads: A, B, C, C, B, A. Determine how far each "C" ad is from your restaurant which is located at mile marker 30.

### Solution

In [1]:
import numpy as np

In [8]:
dists = np.abs(np.linspace([17,32], [28,36], num = 3, axis = 1) - 30)
dists[[0,1], [2,0]] # these are indices for ad C

array([2., 2.])

### Explanation

In [5]:
# linspace Return evenly spaced numbers over a specified interval.
np.linspace(start=0,stop=10,num=5) # generates an array with 5 elements with starting number as 0 and end as 10 and in-between elements to be an equal gap of others. Here the proceeding element is 2.5 value more

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
np.linspace(start=[0,5],stop=[10,15],num=5) # generates an array with 5 sub array elements with starting value as 0,5 and end as 10,15 and inbetween elements to be equal gap of others. Here the proceeding element is 2.5 value more for both row and column

array([[ 0. ,  5. ],
       [ 2.5,  7.5],
       [ 5. , 10. ],
       [ 7.5, 12.5],
       [10. , 15. ]])

In [7]:
np.linspace(start=[0,5],stop=[10,15],num=5, axis=1)

array([[ 0. ,  2.5,  5. ,  7.5, 10. ],
       [ 5. ,  7.5, 10. , 12.5, 15. ]])