### Reshape

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(start = 1, stop = 9)
print(arr1)

[1 2 3 4 5 6 7 8]


In [3]:
arr1.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
np.reshape(a = arr1, newshape = (2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
arr2 = arr1.reshape(2,4)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
arr2.reshape((4,2), order='C') # C order means row major order aka C Style

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [15]:
arr2.reshape((4,2), order='F') # F order means column major order aka Fortan Order
# here all the column are first inserted in row 

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

In [12]:
arr2.reshape((2,2,2), order='C') 

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
arr2.reshape((2,2,2), order='F') 

array([[[1, 3],
        [2, 4]],

       [[5, 7],
        [6, 8]]])

In [16]:
# you can only pass row value in reshape and -1 in column so that numpy will auto calculate the required column vlaue
arr2.reshape(4,-1)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
# reshape creates a new array
# if you want to modify the original array then use shape
arr2.shape = (4,2)
print(arr2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Transform

In [19]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
# transform coverts rows into column and column into row so 4x2 matrix becomes 2x4
arr2.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [21]:
np.transpose(arr2)

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])