### Boolean Indexing

In [1]:
import numpy as np

In [2]:
foo = np.array([
    [3,9,7],
    [2,0,3],
    [3,3,1]
])

In [5]:
mask = foo == 3 
# this mask will be an matrix of boolean value and it will have True as value if the item value is 3

In [4]:
mask

array([[ True, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [7]:
foo[mask] = 0 # this will replace all the value 3 with 0
print(foo)

[[0 9 7]
 [2 0 0]
 [0 0 1]]


In [8]:
# return specific row and columns
rows_1_and_3 = np.array([True, False, True])
cols_2_and_3 = np.array([False, True, True])

In [12]:
foo[rows_1_and_3] # selects like foo[[0,2]] ie first and last row

array([[0, 9, 7],
       [0, 0, 1]])

In [13]:
foo[:, cols_2_and_3]  # selects like foo[:, [1,2]] ie all rows and 1th and 2th index columns

array([[9, 7],
       [0, 0],
       [0, 1]])

In [14]:
foo[rows_1_and_3, cols_2_and_3] # like foo[[0,2], [1,2]]

array([9, 1])

In [17]:
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(['male', 'female', 'male', 'male', 'male'])

In [18]:
# Who's at least 44?
names[ages >= 44]

array(['Dee', 'Frank'], dtype='<U7')

In [19]:
# Which males are over 42?
names[(genders == 'male') & (ages > 42)]

array(['Dennis', 'Charlie', 'Frank'], dtype='<U7')

In [20]:
# Who's not a male or is younger than 43?
names[~(genders == 'male') | (ages < 43)]

array(['Dee', 'Mac'], dtype='<U7')

### Nan

In [21]:
bot = np.ones(shape = (3,4))

bot[(0,2),(1,2)] = np.nan

print(bot)

[[ 1. nan  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1. nan  1.]]


In [22]:
bot == np.nan

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
np.nan == np.nan

False

In [24]:
np.nan != np.nan

True

In [26]:
np.isnan(bot) # gives true for nan element value

array([[False,  True, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [27]:
# you cannot manually assign nan vlaue
foo = np.array([1,2,3], dtype = 'int64')
foo[1] = np.nan

ValueError: cannot convert float NaN to integer

### Infinity

In [28]:
np.array([np.inf, np.NINF])

array([ inf, -inf])

In [29]:
np.array([-1,1]) / 0

C:\Users\Asus\AppData\Local\Temp\ipykernel_10000\2944993110.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([-1,1]) / 0


array([-inf,  inf])

In [30]:
np.inf * 22

inf

In [31]:
np.inf + np.inf

inf

In [32]:
np.inf - np.inf

nan

In [34]:
np.inf / np.inf

nan

In [35]:
np.inf == np.inf

True

In [36]:
np.NINF == np.NINF

True

In [37]:
foo = np.array([4.4, np.inf, 1.0, np.NINF, 3.1, np.inf])

In [40]:
foo == np.inf # returns true if the element is positive infinity

array([False,  True, False, False, False,  True])

In [41]:
foo == np.NINF # returns true if the element is negative infinity

array([False, False, False,  True, False, False])

In [42]:
np.isposinf(foo) # returns true if the element is positive infinity

array([False,  True, False, False, False,  True])

In [44]:
np.isneginf(foo)  # returns true if the element is negative infinity

array([False, False, False,  True, False, False])