In [1]:
import numpy as np

In [2]:
# this will randomly generate the number and will be unique each time you run it
np.random.randint(low=1, high=7, size=3)

array([4, 3, 2])

In [3]:
np.random.randint(low=1, high=7, size=3)

array([2, 3, 2])

In [4]:
# provide a seed to get the same random number every time you run this block of code
np.random.seed(123)
np.random.randint(low=1, high=7, size=3)

array([6, 3, 5])

In [12]:
np.random.seed(2357)
np.random.choice(
    a = np.arange(1,7), # [1,2,3,4,5,6]
    size = 3, # means sample or select 3 values
    replace = False, # meaning the same number will not be selected more than once for the resulting array
    p = None # the p parameter specifies the probabilities associated with each entry in the array a. If p is set to None, it means that each entry in the array a is equally likely to be chosen; that is, the selection is made with a uniform distribution.
    # The code without explicitly using p=None for the probabilities still implies a uniform distribution by default. 
)

array([6, 5, 1])

In [13]:
np.random.choice(
    a = np.arange(1,7), # [1,2,3,4,5,6]
    size = 3, # means sample or select 3 values
    replace = False, # meaning the same number will not be selected more than once for the resulting array
    p = np.array([0.1, 0.1, 0.1, 0.1, 0.3, 0.3]) # the p parameter specifies the probabilities associated with each entry in the array a. 
    # if you wish to provide the probability of occurrence of each element of the array then you must give probability to all elements of the array so p's length must be equal to that of a. And the sum of all probabilities must be 1.
    # Here we are setting the high probability of occurrence to 5 and 6 with 0.3 and rest with 0.1
)

array([5, 2, 6])

### Select randomly from array

In [14]:
foo = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8],
    [9, 10]
])

In [19]:
np.random.seed(1234)
rand_rows = np.random.randint(
    low=0,
    high=foo.shape[0], # gives (5, 2)
    size=3
)

print(rand_rows)

[3 4 4]


In [18]:
foo[rand_rows] # selecting 3rd, 4th and 4th position elements of foo

array([[ 7,  8],
       [ 9, 10],
       [ 9, 10]])

In [20]:
np.random.seed(1234)
rand_rows = np.random.choice(
    a = np.arange(start = 0, stop = foo.shape[0]),
    replace = False,
    size=3
)

print(rand_rows)

[4 0 1]


In [21]:
foo[rand_rows]

array([[ 9, 10],
       [ 1,  2],
       [ 3,  4]])

In [22]:
# use permutation to shuffle the array along with its first axis
np.random.permutation(foo)

array([[ 7,  8],
       [ 5,  6],
       [ 3,  4],
       [ 1,  2],
       [ 9, 10]])

In [28]:
# random unifrom sample
np.random.uniform(low = 1.0, high = 2.0, size = (2,2))
# In a uniform distribution, every number within a specified range has an equal chance of being drawn. There are no numbers in the range that are more likely than others.

array([[1.29072855, 1.24639444],
       [1.73828677, 1.88922613]])

In [27]:
# normal sample
np.random.normal(loc = 0.0, scale = 1.0, size = 2)
# In a normal distribution, numbers are drawn in a way that they are more likely to be close to the mean (central value) and less likely to be at the extremes. It has a characteristic bell curve shape.

array([-0.38786434, -0.04653935])

## New way of generating random number

We just have to define the algorithm so that we get the same output every time.

In [30]:
# create a generator
generator = np.random.default_rng(seed=123)

In [36]:
# Sample three ints between 1 and 6 with replacement
# before: np.randomint(low=1, high=7, size=3)
# now:
generator.integers(low=1, high=7, size=3)

array([3, 6, 3], dtype=int64)

In [35]:
# Sample three ints between 0 and 9 without replacement
# before: np.random.choice(a=10, size=3, replace=True)
generator.choice(a=10, size=3, replace=True)

array([1, 3, 8], dtype=int64)

In [37]:
# Randomly shuffle the rows of a 2d array, foo
# before: np.random.permutation(foo)
generator.permutation(foo, axis=0)

array([[ 9, 10],
       [ 5,  6],
       [ 7,  8],
       [ 1,  2],
       [ 3,  4]])

In [38]:
# Randomly sample values from a uniform distribution
# before: np.random.uniform(low = 1.0, high = 2.0, size = (2, 2))
generator.uniform(low = 1.0, high = 2.0, size = (2, 2))

array([[1.51297046, 1.2449646 ],
       [1.8242416 , 1.21376296]])

In [39]:
# Randomly sample values from a standard normal distribution
# before: np.random.normal(loc = 0.0, scale = 1.0, size = 2)
generator.normal(loc = 0.0, scale = 1.0, size = 2)

array([1.00026942, 0.13632112])

In [40]:
# Randomly sample values from a binomial distribution
# before: np.random.binomial(n = 10, p = 0.25, size = (3,2))
generator.binomial(n = 10, p = 0.25, size = (3,2))

array([[5, 1],
       [4, 2],
       [1, 1]], dtype=int64)