# Challenge 1

You're a relationship scientist and you've developed a questionaire that determines a person's love score, a real-valued number between 0 and
100. Your theory is that two people with similar love scores should make a good match. Given the love scores for 10 different people, create a
matrix where (i,j) gives the absolute difference of the love scores for person i and person j.

In [1]:
import numpy as np

In [2]:
generator = np.random.default_rng(1010)
love_scores = np.round(generator.uniform(low=0, high=100, size=10), 2)

print(love_scores)

[ 9.5  53.58 91.77 98.15 84.88 74.61 40.94 56.49  8.39 64.69]


## Solution

In [5]:
np.set_printoptions(linewidth=999) # means donot wrap the line of text unless it exceed 999 characters. By default it wraps at 75 characters
np.abs(love_scores[:, None] - love_scores[None, :])

array([[ 0.  , 44.08, 82.27, 88.65, 75.38, 65.11, 31.44, 46.99,  1.11, 55.19],
       [44.08,  0.  , 38.19, 44.57, 31.3 , 21.03, 12.64,  2.91, 45.19, 11.11],
       [82.27, 38.19,  0.  ,  6.38,  6.89, 17.16, 50.83, 35.28, 83.38, 27.08],
       [88.65, 44.57,  6.38,  0.  , 13.27, 23.54, 57.21, 41.66, 89.76, 33.46],
       [75.38, 31.3 ,  6.89, 13.27,  0.  , 10.27, 43.94, 28.39, 76.49, 20.19],
       [65.11, 21.03, 17.16, 23.54, 10.27,  0.  , 33.67, 18.12, 66.22,  9.92],
       [31.44, 12.64, 50.83, 57.21, 43.94, 33.67,  0.  , 15.55, 32.55, 23.75],
       [46.99,  2.91, 35.28, 41.66, 28.39, 18.12, 15.55,  0.  , 48.1 ,  8.2 ],
       [ 1.11, 45.19, 83.38, 89.76, 76.49, 66.22, 32.55, 48.1 ,  0.  , 56.3 ],
       [55.19, 11.11, 27.08, 33.46, 20.19,  9.92, 23.75,  8.2 , 56.3 ,  0.  ]])

# Challenge 2

You're a vindictive, hateful professor and one of your pet peeves is when students rush through their exams. To teach them a lesson, you decide
to give 0s to the first three students who score less than sixty, in the order they turned in their exams. So, given a 1d array of integers, identify
the first three values less than sixty and replace them with zero.

In [4]:
import numpy as np

In [8]:
generator = np.random.default_rng(80085)
scores =  np.round(generator.uniform(low=30, high=100, size=15))

print(scores)

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


In [6]:
scores[(scores < 60).nonzero()[0][:3]] = 0
print(scores)

[68.  0. 76.  0.  0. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


### Explanation

In [9]:
# make sure to run the original scores generator cell first as out solution has override it
scores < 60

array([False,  True, False,  True,  True,  True, False, False,  True,
       False, False, False, False, False,  True])

In [12]:
# we are interested in false value as they are the ones with score less than 60
# the integer representation of false is 0
# nonzero returns the indices of the elements that are non-zero
np.array([0,3,4,0]).nonzero()

(array([1, 2], dtype=int64),)

In [16]:
(scores < 60).nonzero() # return the tuple with array and empty nothing

(array([ 1,  3,  4,  5,  8, 14], dtype=int64),)

In [15]:
# get the array only
(scores < 60).nonzero()[0]

array([ 1,  3,  4,  5,  8, 14], dtype=int64)

In [18]:
# get the first three datas indices with :3
(scores < 60).nonzero()[0][:3]

array([1, 3, 4], dtype=int64)

In [20]:
# now assign the first three less than 60 value to 0
scores[(scores < 60).nonzero()[0][:3]] = 0
print(scores)


[68.  0. 76.  0.  0. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


# Challenge 3

Eager to make your mark on the PTA, you decide the best way to hide eggs for for the upcoming easter egg hunt is to use NumPy. You
represent the field as a 10x10 array of Os. Now your goal is to insert twenty random normal values at random (non repeating) locations in the
grid that tell you how much candy to hide at each spot and where.

In [21]:
import numpy as np

In [38]:
field = np.zeros(shape = (10, 10))
print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Solution

In [27]:
np.set_printoptions(linewidth=999)
generator = np.random.default_rng(1234)
vals = np.round(generator.normal(size=20), 2)
locs = generator.choice(field.size, len(vals), replace=False)
field.ravel()[locs] = vals
print(field)

[[ 0.52  0.    0.   -1.48  0.    2.91  0.    0.    0.    0.  ]
 [ 0.   -1.27  0.    0.    0.   -1.6   0.    1.73  0.    0.  ]
 [ 0.    0.    0.    0.    0.43  0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.34  0.    0.    0.   -1.67]
 [ 0.    0.86  0.74  0.    0.    0.    1.32  0.    0.52  0.  ]
 [ 0.   -1.    0.    0.    0.    0.15  0.    0.    0.    0.  ]
 [ 0.   -0.51  0.   -0.86  0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.   -2.16  0.    0.95  0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.06]]


### Explanation

In [31]:
# generate 20 normal values
generator = np.random.default_rng(1234)
np.round(generator.normal(size=20), 2)

array([-1.6 ,  0.06,  0.74,  0.15,  0.86,  2.91, -1.48,  0.95, -1.67,  0.34, -0.51,  1.32, -0.86,  0.52, -1.27, -2.16,  0.43,  1.73,  0.52, -1.  ])

In [32]:
# round random values to 2 digits
generator = np.random.default_rng(1234)
vals = np.round(generator.normal(size=20), 2)
print(vals)

[-1.6   0.06  0.74  0.15  0.86  2.91 -1.48  0.95 -1.67  0.34 -0.51  1.32 -0.86  0.52 -1.27 -2.16  0.43  1.73  0.52 -1.  ]


In [36]:
# field size is 100 and vals length is 10
# here generating the 20 random array position from 0 to 99
locs = generator.choice(field.size, len(vals), replace=False)
print(locs)

[39  3 12 83 96 57 99 47 77 85 23 74 29  6 18  1 95 11 89 73]


In [39]:
# ravel method flatens the array to 1 dimensional
field.ravel()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
# but the flatening is one for easy view coz in reality it still remains in high dimensional
print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
# after the flatening we just map the field array with the randomly generated 20 indices postion
field.ravel()[locs] = vals
print(field)

[[ 0.   -2.16  0.    0.06  0.    0.    0.52  0.    0.    0.  ]
 [ 0.    1.73  0.74  0.    0.    0.    0.    0.   -1.27  0.  ]
 [ 0.    0.    0.   -0.51  0.    0.    0.    0.    0.   -0.86]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.   -1.6 ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.95  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    2.91  0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.   -1.    1.32  0.    0.   -1.67  0.    0.  ]
 [ 0.    0.    0.    0.15  0.    0.34  0.    0.    0.    0.52]
 [ 0.    0.    0.    0.    0.    0.43  0.86  0.    0.   -1.48]]
